version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: dungeondex
      MYSQL_USER: dungeondex
      MYSQL_PASSWORD: dungeondex
    volumes:
      - ./database:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql # mount the database.sql file as a volume
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - "5430:3306"
  admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret123
    ports:
      - "5431:80"
